#include <stdexcept>
int main() {
  throw std::runtime_error("abort");
}
